using DBML;
using IBase;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Linq;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Utility;

namespace DAL
{
    public class DataSourcesDAL : IDALBase
    {

        public Dictionary<Type, object> GetVDataSources(DCC dcc)
        {
            IMultipleResults dataSources = dcc.USPGetDataSources();
            Dictionary<Type, object> dataSourceList = new Dictionary<Type, object>();
            dataSourceList.Add(typeof(VStockInBill), dataSources.GetResult<VStockInBill>().OrderBy(o => o.SerialNo).OrderBy(o => o.状态).OrderByDescending(o => o.入库单号).ToList());
            dataSourceList.Add(typeof(VStockOutBill), dataSources.GetResult<VStockOutBill>().OrderBy(o => o.SerialNo).OrderBy(o => o.状态).OrderByDescending(o => o.出库单号).ToList());
            dataSourceList.Add(typeof(VMaterialStockInBill), dataSources.GetResult<VMaterialStockInBill>().OrderBy(o => o.SerialNo).OrderBy(o => o.状态).OrderByDescending(o => o.入库单号).ToList());
            dataSourceList.Add(typeof(VMaterialStockOutBill), dataSources.GetResult<VMaterialStockOutBill>().OrderBy(o => o.SerialNo).OrderBy(o => o.状态).OrderByDescending(o => o.出库单号).ToList());
            dataSourceList.Add(typeof(StockInBillHd), dataSources.GetResult<StockInBillHd>().OrderBy(o => o.BillNo).ToList());
            dataSourceList.Add(typeof(StockOutBillHd), dataSources.GetResult<StockOutBillHd>().OrderBy(o => o.BillNo).ToList());
            dataSourceList.Add(typeof(OrderHd), dataSources.GetResult<OrderHd>().OrderBy(o => o.BillNo).ToList());
            dataSourceList.Add(typeof(ReceiptBillHd), dataSources.GetResult<ReceiptBillHd>().OrderBy(o => o.BillNo).ToList());
            dataSourceList.Add(typeof(PaymentBillHd), dataSources.GetResult<PaymentBillHd>().OrderBy(o => o.BillNo).ToList());
            dataSourceList.Add(typeof(VPO), dataSources.GetResult<VPO>().OrderBy(o => o.订货单号).ToList());
            dataSourceList.Add(typeof(VOrder), dataSources.GetResult<VOrder>().OrderBy(o => o.SerialNo).OrderBy(o => o.状态).OrderByDescending(o => o.订货单号).ToList());
            dataSourceList.Add(typeof(VFSMOrder), dataSources.GetResult<VFSMOrder>().OrderByDescending(o => o.类型).OrderBy(o => o.状态).ToList());
            dataSourceList.Add(typeof(VProductionOrder), dataSources.GetResult<VProductionOrder>().OrderByDescending(o => o.类型).OrderBy(o => o.状态).ToList());
            dataSourceList.Add(typeof(VInventory), dataSources.GetResult<VInventory>().OrderBy(o => o.登帐日期).ToList());
            dataSourceList.Add(typeof(VInventoryGroupByGoods), dataSources.GetResult<VInventoryGroupByGoods>().OrderBy(o => o.货号).ToList());
            dataSourceList.Add(typeof(VMaterialInventory), dataSources.GetResult<VMaterialInventory>().OrderBy(o => o.登帐日期).ToList());
            dataSourceList.Add(typeof(VMaterialInventoryGroupByGoods), dataSources.GetResult<VMaterialInventoryGroupByGoods>().OrderBy(o => o.货号).ToList());
            dataSourceList.Add(typeof(VEMSInventoryGroupByGoods), dataSources.GetResult<VEMSInventoryGroupByGoods>().OrderBy(o => o.货号).ToList());
            dataSourceList.Add(typeof(VFSMInventoryGroupByGoods), dataSources.GetResult<VFSMInventoryGroupByGoods>().OrderBy(o => o.货号).ToList());
            dataSourceList.Add(typeof(VAccountBook), dataSources.GetResult<VAccountBook>().OrderBy(o => o.记帐日期).ToList());
            dataSourceList.Add(typeof(StocktakingLogHd), dataSources.GetResult<StocktakingLogHd>().OrderBy(o => o.BillDate).ToList());
            dataSourceList.Add(typeof(VStocktakingLog), dataSources.GetResult<VStocktakingLog>().OrderBy(o => o.DeptCode).OrderBy(o => o.BillNo).OrderBy(o => o.GoodsCode).ToList());
            dataSourceList.Add(typeof(VProfitAndLossLog), dataSources.GetResult<VProfitAndLossLog>().OrderBy(o => o.DeptCode).OrderBy(o => o.BillNo).OrderBy(o => o.GoodsCode).ToList());
            dataSourceList.Add(typeof(VUnlistedGoodsLog), dataSources.GetResult<VUnlistedGoodsLog>().OrderBy(o => o.DeptCode).OrderBy(o => o.BillNo).OrderBy(o => o.GoodsCode).ToList());
            dataSourceList.Add(typeof(SalesSummaryMonthlyReport), dataSources.GetResult<SalesSummaryMonthlyReport>().ToList());
            dataSourceList.Add(typeof(AnnualSalesSummaryByCustomerReport), dataSources.GetResult<AnnualSalesSummaryByCustomerReport>().ToList());
            dataSourceList.Add(typeof(AnnualSalesSummaryByGoodsReport), dataSources.GetResult<AnnualSalesSummaryByGoodsReport>().ToList());
            dataSourceList.Add(typeof(VSalesBillSummary), new List<VSalesBillSummary>());
            dataSourceList.Add(typeof(VProductionOrderDtlForPrint), dataSources.GetResult<VProductionOrderDtlForPrint>().OrderBy(o => o.货号).ToList());
            dataSourceList.Add(typeof(VAlert), dataSources.GetResult<VAlert>().ToList());
            dataSourceList.Add(typeof(Alert), dataSources.GetResult<Alert>().ToList());
            dataSourceList.Add(typeof(VReceiptBillDtl), dataSources.GetResult<VReceiptBillDtl>().OrderBy(o => o.BillNo).ToList());
            dataSourceList.Add(typeof(VReceiptBill), dataSources.GetResult<VReceiptBill>().OrderBy(o => o.状态).OrderByDescending(o => o.收款单号).ToList());
            dataSourceList.Add(typeof(VPaymentBillDtl), dataSources.GetResult<VPaymentBillDtl>().OrderBy(o => o.BillDate).OrderBy(o => o.Type).ToList());
            dataSourceList.Add(typeof(VPaymentBill), dataSources.GetResult<VPaymentBill>().OrderBy(o => o.状态).OrderByDescending(o => o.付款单号).ToList());
            dataSourceList.Add(typeof(StatementOfAccountToBulkSalesReport), dataSources.GetResult<StatementOfAccountToBulkSalesReport>().ToList());
            dataSourceList.Add(typeof(StatementOfAccountToCustomerReport), dataSources.GetResult<StatementOfAccountToCustomerReport>().ToList());//.OrderBy(o => o.结算类型).OrderBy(o => o.出库日期).ToList());
            dataSourceList.Add(typeof(StatementOfAccountToSupplierReport), dataSources.GetResult<StatementOfAccountToSupplierReport>().ToList());//.OrderBy(o => o.结算类型).OrderBy(o => o.结算日期).ToList());
            dataSourceList.Add(typeof(VCustomerSettlement), dataSources.GetResult<VCustomerSettlement>().ToList());
            dataSourceList.Add(typeof(VSupplierSettlement), dataSources.GetResult<VSupplierSettlement>().ToList());
            dataSourceList.Add(typeof(VSampleStockOut), dataSources.GetResult<VSampleStockOut>().OrderBy(o => o.SerialNo).OrderBy(o => o.状态).OrderByDescending(o => o.出库单号).ToList());
            dataSourceList.Add(typeof(Resources), dataSources.GetResult<Resources>().ToList());
            dataSourceList.Add(typeof(Appointments), dataSources.GetResult<Appointments>().ToList());
            dataSourceList.Add(typeof(VAppointments), dataSources.GetResult<VAppointments>().ToList());
            dataSourceList.Add(typeof(WageDesign), dataSources.GetResult<WageDesign>().ToList());
            dataSourceList.Add(typeof(WageBillHd), dataSources.GetResult<WageBillHd>().ToList());
            dataSourceList.Add(typeof(WageBillDtl), dataSources.GetResult<WageBillDtl>().ToList());
            dataSourceList.Add(typeof(VWageBillDtl), dataSources.GetResult<VWageBillDtl>().ToList());
            dataSourceList.Add(typeof(VWageBill), dataSources.GetResult<VWageBill>().ToList());
            dataSourceList.Add(typeof(SalesSummaryByCustomerReport), new List<SalesSummaryByCustomerReport>());
            dataSourceList.Add(typeof(SalesSummaryByGoodsReport), new List<SalesSummaryByGoodsReport>());
            dataSourceList.Add(typeof(SalesSummaryByGoodsPriceReport), new List<SalesSummaryByGoodsPriceReport>());
            dataSourceList.Add(typeof(GoodsSalesSummaryByCustomerReport), new List<GoodsSalesSummaryByCustomerReport>());
            dataSourceList.Add(typeof(AttGeneralLog), dataSources.GetResult<AttGeneralLog>().OrderBy(o => o.AttTime).ToList());
            dataSourceList.Add(typeof(VAttGeneralLog), dataSources.GetResult<VAttGeneralLog>().OrderBy(o => o.出勤时间).ToList());
            dataSourceList.Add(typeof(AttAppointments), dataSources.GetResult<AttAppointments>().OrderBy(o => o.CheckInTime).ToList());
            dataSourceList.Add(typeof(VAttAppointments), dataSources.GetResult<VAttAppointments>().ToList());
            dataSourceList.Add(typeof(AttWageBillHd), dataSources.GetResult<AttWageBillHd>().ToList());
            dataSourceList.Add(typeof(AttWageBillDtl), dataSources.GetResult<AttWageBillDtl>().ToList());
            dataSourceList.Add(typeof(USPAttWageBillDtl), dataSources.GetResult<USPAttWageBillDtl>().ToList());
            dataSourceList.Add(typeof(VAttWageBill), dataSources.GetResult<VAttWageBill>().ToList());
            dataSources.Dispose();
            System.GC.Collect();
            return dataSourceList;
        }
        public Dictionary<Type, object> GetDataSources(DCC dcc)
        {
            IMultipleResults dataSources = dcc.USPGetDataBaseSources();
            Dictionary<Type, object> dataSourceList = new Dictionary<Type, object>();
            dataSourceList.Add(typeof(DBML.MainMenu), dataSources.GetResult<DBML.MainMenu>().OrderBy(o => o.SerialNo).ToList());
            dataSourceList.Add(typeof(SystemStatus), dataSources.GetResult<SystemStatus>().ToList());
            dataSourceList.Add(typeof(Permission), dataSources.GetResult<Permission>().OrderBy(o => o.SerialNo).ToList());
            dataSourceList.Add(typeof(ButtonPermission), dataSources.GetResult<ButtonPermission>().OrderBy(o => o.ID).ToList());
            dataSourceList.Add(typeof(SystemInfo), dataSources.GetResult<SystemInfo>().ToList());
            dataSourceList.Add(typeof(TypesList), dataSources.GetResult<TypesList>().ToList());
            dataSourceList.Add(typeof(Warehouse), dataSources.GetResult<Warehouse>().ToList());
            dataSourceList.Add(typeof(Department), dataSources.GetResult<Department>().OrderBy(o => o.Code).ToList());
            dataSourceList.Add(typeof(VCompany), dataSources.GetResult<VCompany>().OrderBy(o => o.代码).ToList());
            dataSourceList.Add(typeof(Company), dataSources.GetResult<Company>().OrderBy(o => o.Code).ToList());
            dataSourceList.Add(typeof(VSupplier), dataSources.GetResult<VSupplier>().OrderBy(o => o.代码).ToList());
            dataSourceList.Add(typeof(Supplier), dataSources.GetResult<Supplier>().OrderBy(o => o.Code).ToList());
            dataSourceList.Add(typeof(VUsersInfo), dataSources.GetResult<VUsersInfo>().ToList());
            dataSourceList.Add(typeof(UsersInfo), dataSources.GetResult<UsersInfo>().ToList());
            dataSourceList.Add(typeof(GoodsType), dataSources.GetResult<GoodsType>().OrderBy(o => o.Code).ToList());
            dataSourceList.Add(typeof(VGoodsType), dataSources.GetResult<VGoodsType>().OrderBy(o => o.类型编码).ToList());
            dataSourceList.Add(typeof(Goods), dataSources.GetResult<Goods>().OrderBy(o => o.Code).ToList());
            dataSourceList.Add(typeof(VMaterial), dataSources.GetResult<VMaterial>().OrderBy(o => o.货号).ToList());
            dataSourceList.Add(typeof(VGoodsByBOM), dataSources.GetResult<VGoodsByBOM>().OrderBy(o => o.货号).ToList());
            dataSourceList.Add(typeof(VParentGoodsByBOM), dataSources.GetResult<VParentGoodsByBOM>().OrderBy(o => o.货号).ToList());
            dataSourceList.Add(typeof(VGoodsByMoldAllot), dataSources.GetResult<VGoodsByMoldAllot>().OrderBy(o => o.货号).ToList());
            dataSourceList.Add(typeof(VGoodsBySLSalePrice), dataSources.GetResult<VGoodsBySLSalePrice>().OrderBy(o => o.货号).ToList());
            dataSourceList.Add(typeof(VPackaging), dataSources.GetResult<VPackaging>().ToList());
            dataSourceList.Add(typeof(Packaging), dataSources.GetResult<Packaging>().ToList());
            dataSourceList.Add(typeof(BOM), dataSources.GetResult<BOM>().ToList());
            dataSourceList.Add(typeof(MoldAllot), dataSources.GetResult<MoldAllot>().ToList());
            dataSourceList.Add(typeof(SLSalePrice), dataSources.GetResult<SLSalePrice>().ToList());
            dataSourceList.Add(typeof(AttParameters), dataSources.GetResult<AttParameters>().ToList());
            dataSourceList.Add(typeof(SchClass), dataSources.GetResult<SchClass>().OrderBy(o => o.SerialNo).ToList());
            dataSourceList.Add(typeof(StaffSchClass), dataSources.GetResult<StaffSchClass>().ToList());
            dataSourceList.Add(typeof(VStaffSchClass), dataSources.GetResult<VStaffSchClass>().ToList());
            dataSourceList.Add(typeof(Stocktaking), dataSources.GetResult<Stocktaking>().OrderBy(o => o.CheckingDate).ToList());
            dataSourceList.Add(typeof(ProfitAndLoss), dataSources.GetResult<ProfitAndLoss>().OrderBy(o => o.GoodsCode).ToList());
            dataSourceList.Add(typeof(UnlistedGoods), dataSources.GetResult<UnlistedGoods>().OrderBy(o => o.GoodsCode).ToList());
            //异步
            dataSourceList.Add(typeof(VStockInBill), dataSources.GetResult<VStockInBill>());
            dataSourceList.Add(typeof(VStockOutBill), dataSources.GetResult<VStockOutBill>());
            dataSourceList.Add(typeof(VMaterialStockInBill), dataSources.GetResult<VMaterialStockInBill>());
            dataSourceList.Add(typeof(VMaterialStockOutBill), dataSources.GetResult<VMaterialStockOutBill>());
            dataSourceList.Add(typeof(StockInBillHd), dataSources.GetResult<StockInBillHd>());
            dataSourceList.Add(typeof(StockOutBillHd), dataSources.GetResult<StockOutBillHd>());
            dataSourceList.Add(typeof(OrderHd), dataSources.GetResult<OrderHd>());
            dataSourceList.Add(typeof(ReceiptBillHd), dataSources.GetResult<ReceiptBillHd>());
            dataSourceList.Add(typeof(PaymentBillHd), dataSources.GetResult<PaymentBillHd>());
            dataSourceList.Add(typeof(VPO), dataSources.GetResult<VPO>());
            dataSourceList.Add(typeof(VOrder), dataSources.GetResult<VOrder>());
            dataSourceList.Add(typeof(VFSMOrder), dataSources.GetResult<VFSMOrder>());
            dataSourceList.Add(typeof(VProductionOrder), dataSources.GetResult<VProductionOrder>());
            dataSourceList.Add(typeof(VInventory), dataSources.GetResult<VInventory>());
            dataSourceList.Add(typeof(VInventoryGroupByGoods), dataSources.GetResult<VInventoryGroupByGoods>());
            dataSourceList.Add(typeof(VMaterialInventory), dataSources.GetResult<VMaterialInventory>());
            dataSourceList.Add(typeof(VMaterialInventoryGroupByGoods), dataSources.GetResult<VMaterialInventoryGroupByGoods>());
            dataSourceList.Add(typeof(VEMSInventoryGroupByGoods), dataSources.GetResult<VEMSInventoryGroupByGoods>());
            dataSourceList.Add(typeof(VFSMInventoryGroupByGoods), dataSources.GetResult<VFSMInventoryGroupByGoods>());
            dataSourceList.Add(typeof(VAccountBook), dataSources.GetResult<VAccountBook>());
            dataSourceList.Add(typeof(StocktakingLogHd), dataSources.GetResult<StocktakingLogHd>());
            dataSourceList.Add(typeof(VStocktakingLog), dataSources.GetResult<VStocktakingLog>());
            dataSourceList.Add(typeof(VProfitAndLossLog), dataSources.GetResult<VProfitAndLossLog>());
            dataSourceList.Add(typeof(VUnlistedGoodsLog), dataSources.GetResult<VUnlistedGoodsLog>());
            dataSourceList.Add(typeof(SalesSummaryMonthlyReport), dataSources.GetResult<SalesSummaryMonthlyReport>());
            dataSourceList.Add(typeof(AnnualSalesSummaryByCustomerReport), dataSources.GetResult<AnnualSalesSummaryByCustomerReport>());
            dataSourceList.Add(typeof(AnnualSalesSummaryByGoodsReport), dataSources.GetResult<AnnualSalesSummaryByGoodsReport>());
            dataSourceList.Add(typeof(VSalesBillSummary), new List<VSalesBillSummary>());
            dataSourceList.Add(typeof(VProductionOrderDtlForPrint), dataSources.GetResult<VProductionOrderDtlForPrint>());
            dataSourceList.Add(typeof(VAlert), dataSources.GetResult<VAlert>());
            dataSourceList.Add(typeof(Alert), dataSources.GetResult<Alert>());
            dataSourceList.Add(typeof(VReceiptBillDtl), dataSources.GetResult<VReceiptBillDtl>());
            dataSourceList.Add(typeof(VReceiptBill), dataSources.GetResult<VReceiptBill>());
            dataSourceList.Add(typeof(VPaymentBillDtl), dataSources.GetResult<VPaymentBillDtl>());
            dataSourceList.Add(typeof(VPaymentBill), dataSources.GetResult<VPaymentBill>());
            dataSourceList.Add(typeof(StatementOfAccountToBulkSalesReport), dataSources.GetResult<StatementOfAccountToBulkSalesReport>());
            dataSourceList.Add(typeof(StatementOfAccountToCustomerReport), dataSources.GetResult<StatementOfAccountToCustomerReport>());
            dataSourceList.Add(typeof(StatementOfAccountToSupplierReport), dataSources.GetResult<StatementOfAccountToSupplierReport>());
            dataSourceList.Add(typeof(VCustomerSettlement), dataSources.GetResult<VCustomerSettlement>());
            dataSourceList.Add(typeof(VSupplierSettlement), dataSources.GetResult<VSupplierSettlement>());
            dataSourceList.Add(typeof(VSampleStockOut), dataSources.GetResult<VSampleStockOut>());
            dataSourceList.Add(typeof(Resources), dataSources.GetResult<Resources>());
            dataSourceList.Add(typeof(Appointments), dataSources.GetResult<Appointments>());
            dataSourceList.Add(typeof(VAppointments), dataSources.GetResult<VAppointments>());
            dataSourceList.Add(typeof(WageDesign), dataSources.GetResult<WageDesign>());
            dataSourceList.Add(typeof(WageBillHd), dataSources.GetResult<WageBillHd>());
            dataSourceList.Add(typeof(WageBillDtl), dataSources.GetResult<WageBillDtl>());
            dataSourceList.Add(typeof(VWageBillDtl), dataSources.GetResult<VWageBillDtl>());
            dataSourceList.Add(typeof(VWageBill), dataSources.GetResult<VWageBill>());
            dataSourceList.Add(typeof(SalesSummaryByCustomerReport), new List<SalesSummaryByCustomerReport>());
            dataSourceList.Add(typeof(SalesSummaryByGoodsReport), new List<SalesSummaryByGoodsReport>());
            dataSourceList.Add(typeof(SalesSummaryByGoodsPriceReport), new List<SalesSummaryByGoodsPriceReport>());
            dataSourceList.Add(typeof(GoodsSalesSummaryByCustomerReport), new List<GoodsSalesSummaryByCustomerReport>());
            dataSourceList.Add(typeof(AttGeneralLog), dataSources.GetResult<AttGeneralLog>());
            dataSourceList.Add(typeof(VAttGeneralLog), dataSources.GetResult<VAttGeneralLog>());
            dataSourceList.Add(typeof(AttAppointments), dataSources.GetResult<AttAppointments>());
            dataSourceList.Add(typeof(VAttAppointments), dataSources.GetResult<VAttAppointments>());
            dataSourceList.Add(typeof(AttWageBillHd), dataSources.GetResult<AttWageBillHd>());
            dataSourceList.Add(typeof(AttWageBillDtl), dataSources.GetResult<AttWageBillDtl>());
            dataSourceList.Add(typeof(USPAttWageBillDtl), dataSources.GetResult<USPAttWageBillDtl>());
            dataSourceList.Add(typeof(VAttWageBill), dataSources.GetResult<VAttWageBill>());
            dataSources.Dispose();
            System.GC.Collect();
            return dataSourceList;
        }
    }
}
